jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-slim
        auth:
          username: mydockerusername
          password: dockerhubpassword  # context / project UI env-var reference
    steps:
      - checkout

      - run: mvn clean package
